services:
  database:
    restart: unless-stopped
    build:
      context: ./sql
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - '3306:3306'
      
  app:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/app
    depends_on:
      - database
    ports:
      - '80:80'
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - database
      
volumes:
    mysql: